services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5000:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - localprom
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
  
  migrator:
    image: locoapp:0.0.3
    command: sh -c "cargo loco db migrate"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - localprom
    ports:
      - '5150:5150'

  locoapp:
    image: locoapp:0.0.3
    container_name: locoapp
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    env_file:
      - ./.env
    networks:
      - localprom
    ports:
      - '5150:5150'
    restart: on-failure

volumes:
  postgresDB:

networks:
  localprom:
    driver: bridge
