services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5000:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - localprom
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  postgresDB:

networks:
  localprom:
    driver: bridge